- name: "Main playbook for the laptop"
  hosts: poma-laptop

  vars:
    systemwide_env:
      - key: EDITOR
        value: vim
      - key: BROWSER 
        value: google-chrome-stable
      # make java programs (I mean jetbrains) work with wayland
      - key: _JAVA_AWT_WM_NONREPARENTING
        value: '1'

  tasks:
    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel
    
    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'
    
    - name: "Install AUR package manager yay"
      package:
        name:
          - yay
        state: present

    - name: 'instal Multimedia packages'
      package:
        name:
          - mpv
          - ffmpeg
          - youtube-dl
        state: present

    - name: 'instal Multimedia packages yay'
      kewlfft.aur.aur:
        name:
          - sbagen
        use: yay
        state: present
      become: yes
      become_user: aur_builder

    - name: 'Install connectivity packages'
      package:
        name:
          - kdeconnect
          - blueberry
            
    - name: 'Install utility packages'
      package:
        name:
          - gimp
          - vim
            
    - name: 'Setup environment variables'
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ systemwide_env }}"
